pull_request_rules:
- actions:
    merge:
      method: squash
      rebase_fallback: merge
  conditions:
  - base=master
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - status-success:
    - review/gitmate/pr
    - 'ci/circleci: prepare'
    - 'ci/circleci: format'
    - 'ci/circleci: lint'
    - 'ci/circleci: test'
  name: master
