rules:
  default:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        contexts:
        - review/gitmate/pr
        - 'ci/circleci: wct-chrome'
        - 'ci/circleci: wct-firefox'
    merge_strategy:
      method: squash
