defaults: &defaults
  working_directory: ~/repo

version: 2
jobs:
  wct-chrome:
    <<: *defaults
    docker:
      - image: circleci/node:8.9.4-browsers
    environment:
      - RYR_GLOBAL_CONFIG_DIR: "/root/.config/ryr"

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-bower-{{ checksum "bower.json" }}

      - run:
          name: Prepare the test environment
          command: |
            sudo  mkdir -p "${RYR_GLOBAL_CONFIG_DIR}"
            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
            sudo  make bootstrap-npm setup

      - save_cache:
          key: dependency-cache-bower-{{ checksum "bower.json" }}
          paths:
            - .node_modules

      - run:
          name: Run the linters
          command: make ci-linters

      - run:
          name: Run unit tests
          command: sudo polymer test -l chrome

      - run:
          name: Run doc tests
          command: make ci-docs

  wct-firefox:
    <<: *defaults
    docker:
      - image: selenium/standalone-firefox:3.11.0
    environment:
      - RYR_GLOBAL_CONFIG_DIR: "/home/seluser/.config/ryr"

    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-bower-{{ checksum "bower.json" }}

      - run:
          name: Install system tools
          command: |
            sudo apt-get update
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends \
              curl \
              git \
              make
            curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
            DEBIAN_FRONTEND=noninteractive sudo apt-get install -y --no-install-recommends \
              nodejs
            npm -v
            npm install npm@latest -g.

      - run:
          name: Prepare the test environment
          command: |
            sudo mkdir -p "${RYR_GLOBAL_CONFIG_DIR}"
            sudo touch "${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
            sudo bash -c "echo 'RYR_WEB_GOOGLE_MAPS_API_KEY=foo' > ${RYR_GLOBAL_CONFIG_DIR}/ryr-env.sh"
            sudo make bootstrap-npm setup

      - save_cache:
          key: dependency-cache-bower-{{ checksum "bower.json" }}
          paths:
            - .node_modules

      - run:
          name: Run the linters
          command: make ci-linters

      - run:
          name: Run unit tests
          command: |
            sudo chown -R $USER:$(id -gn $USER) /home/seluser/.config
            sudo polymer test -l firefox

      - run:
          name: Run doc tests
          command: make ci-docs

workflows:
  version: 2
  wct:
    jobs:
      - wct-chrome
      - wct-firefox
