ingress:
  enabled: true
  hosts:
    - www.requestyoracks.org
  annotations:
    kubernetes.io/ingress.class: nginx
  tls:
    - secretName: requestyoracks-org-tls
      hosts:
        - www.requestyoracks.org

persistence:
  enabled: false

service:
  type: ClusterIP
  externalPort: 80
  internalPort: 80
